exports.seed = function(knex, Promise) {

  return knex('fins').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('fins').insert({fin: 314, reg: 'C-FHJU', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 315, reg: 'C-FHKA', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 316, reg: 'C-FHKE', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 317, reg: 'C-FHKI', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 318, reg: 'C-FHKP', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 321, reg: 'C-FHNL', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 322, reg: 'C-FHNP', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 323, reg: 'C-FHNV', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 324, reg: 'C-FHNW', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 327, reg: 'C-FLWE', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 328, reg: 'C-FLWH', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 329, reg: 'C-FLWK', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 331, reg: 'C-FHOS', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 332, reg: 'C-FHOY', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 333, reg: 'C-FMYV', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 334, reg: 'C-FMZB', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 335, reg: 'C-FMZD', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 336, reg: 'C-FMZR', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 337, reg: 'C-FMZU', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 338, reg: 'C-FMZW', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 339, reg: 'C-FNAI', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 340, reg: 'C-FNAJ', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 341, reg: 'C-FNAN', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 342, reg: 'C-FNAP', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 344, reg: 'C-FNAW', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({fin: 258, reg: 'C-FYJI', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 260, reg: 'C-FYKC', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 261, reg: 'C-FYKR', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 264, reg: 'C-FZUH', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 265, reg: 'C-FZUJ', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 266, reg: 'C-FZUL', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 267, reg: 'C-GAPY', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 268, reg: 'C-GAQL', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 269, reg: 'C-GAQX', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 270, reg: 'C-GAQZ', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 271, reg: 'C-GARG', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 274, reg: 'C-GBHM', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 275, reg: 'C-GBHN', type: 'A319', specific_type: 'A319-100', comments: 'Jetz', operator: 'Air Canada'}),
        knex('fins').insert({fin: 280, reg: 'C-GBIA', type: 'A319', specific_type: 'A319-100', comments: 'Jetz', operator: 'Air Canada'}),
        knex('fins').insert({fin: 282, reg: 'C-GBIK', type: 'A319', specific_type: 'A319-100', comments: 'Jetz', operator: 'Air Canada'}),
        knex('fins').insert({fin: 285, reg: 'C-GBIP', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 286, reg: 'C-GITP', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 287, reg: 'C-GITR', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({fin: 201, reg: 'C-FDQQ', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 202, reg: 'C-FDQV', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 203, reg: 'C-FDRH', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 204, reg: 'C-FDRK', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 205, reg: 'C-FDRP', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 206, reg: 'C-FDSN', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 207, reg: 'C-FDST', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 208, reg: 'C-FDSU', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 209, reg: 'C-FFWI', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 210, reg: 'C-FFWJ', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 211, reg: 'C-FFWM', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 212, reg: 'C-FFWN', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 213, reg: 'C-FTJO', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 215, reg: 'C-FTJQ', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 216, reg: 'C-FTJR', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 217, reg: 'C-FTJS', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 218, reg: 'C-FGYL', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 219, reg: 'C-FGYS', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 220, reg: 'C-FKCK', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 221, reg: 'C-FKCO', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 222, reg: 'C-FKCR', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 225, reg: 'C-FKPT', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 226, reg: 'C-FKOJ', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 228, reg: 'C-FPDN', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 232, reg: 'C-FMSX', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 235, reg: 'C-GJVT', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({fin: 236, reg: 'C-GKOD', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({fin: 237, reg: 'C-GKOE', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({fin: 238, reg: 'C-FZUB', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({fin: 239, reg: 'C-FXCD', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({fin: 240, reg: 'C-FZQS', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({fin: 241, reg: 'C-FGJI', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({fin: 242, reg: 'C-FGKH', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 401, reg: 'C-GPWG', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 402, reg: 'C-FPWE', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 403, reg: 'C-GQCA', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 404, reg: 'C-FPWD', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 405, reg: 'C-FDCA', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 408, reg: 'C-FLSS', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 411, reg: 'C-FLSU', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 415, reg: 'C-FNVU', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 416, reg: 'C-FNVV', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 451, reg: 'C-GITU', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 452, reg: 'C-GITY', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 453, reg: 'C-GIUB', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 454, reg: 'C-GIUE', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 455, reg: 'C-GIUF', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 456, reg: 'C-GJVX', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 457, reg: 'C-GJWD', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 458, reg: 'C-GJWI', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 459, reg: 'C-GJWN', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 460, reg: 'C-GJWO', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 461, reg: 'C-FGKN', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 462, reg: 'C-FGKP', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 463, reg: 'C-FGKZ', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 464, reg: 'C-FJNX', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 473, reg: 'C-FLKX', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({fin: 637, reg: 'C-FPCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 638, reg: 'C-FTCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 639, reg: 'C-FXCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 640, reg: 'C-FOCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 641, reg: 'C-GLCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 681, reg: 'C-FCAB', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 682, reg: 'C-FCAE', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 683, reg: 'C-FCAF', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 684, reg: 'C-FCAG', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 685, reg: 'C-GHOZ', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 701, reg: 'C-FIUA', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({fin: 702, reg: 'C-FIUF', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({fin: 703, reg: 'C-FIUJ', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({fin: 704, reg: 'C-FIVK', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({fin: 705, reg: 'C-FNND', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({fin: 706, reg: 'C-FNNH', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({fin: 731, reg: 'C-FITL', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 732, reg: 'C-FITU', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 733, reg: 'C-FITW', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 734, reg: 'C-FIUL', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 735, reg: 'C-FIUR', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 736, reg: 'C-FIUV', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 737, reg: 'C-FIUW', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 738, reg: 'C-FIVM', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 739, reg: 'C-FRAM', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 740, reg: 'C-FIVQ', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 741, reg: 'C-FIVR', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 742, reg: 'C-FIVS', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 743, reg: 'C-FIVW', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 744, reg: 'C-FIVX', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 745, reg: 'C-FNNQ', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 746, reg: 'C-FNNU', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 747, reg: 'C-FNNW', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 748, reg: 'C-FJZS', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 749, reg: 'C-FKAU', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({fin: 801, reg: 'C-GHPQ', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({fin: 802, reg: 'C-GHPT', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({fin: 803, reg: 'C-GHPU', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({fin: 804, reg: 'C-GHPV', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({fin: 805, reg: 'C-GHPX', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({fin: 806, reg: 'C-GHPY', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({fin: 807, reg: 'C-GHQQ', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({fin: 808, reg: 'C-GHQY', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({fin: 831, reg: 'C-FNOE', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 832, reg: 'C-FNOG', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 833, reg: 'C-FNOH', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 834, reg: 'C-FNOI', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 835, reg: 'C-FGDT', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 836, reg: 'C-FGDX', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 837, reg: 'C-FGDZ', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 838, reg: 'C-FGEI', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 839, reg: 'C-FGEO', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 840, reg: 'C-FGFZ', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 841, reg: 'C-FPQB', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 842, reg: 'C-FGHZ', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 843, reg: 'C-FKSV', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 844, reg: 'C-FRSA', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 845, reg: 'C-FRSE', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 846, reg: 'C-FRSI', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 847, reg: 'C-FRSO', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 848, reg: 'C-FRSR', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 849, reg: 'C-FRTG', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 850, reg: 'C-FRTU', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 851, reg: 'C-FRTW', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({fin: 931, reg: 'C-GFAF', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({fin: 932, reg: 'C-GFAH', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({fin: 933, reg: 'C-GFAJ', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({fin: 934, reg: 'C-GFUR', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({fin: 935, reg: 'C-GHKR', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({fin: 936, reg: 'C-GHKW', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({fin: 937, reg: 'C-GHKX', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({fin: 938, reg: 'C-GHLM', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({fin: 251, reg: 'C-FYNS', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 252, reg: 'C-FYIY', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 255, reg: 'C-FYJE', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 256, reg: 'C-FYJG', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 257, reg: 'C-FYJH', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 259, reg: 'C-FYJP', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 262, reg: 'C-FYKW', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 263, reg: 'C-FZUG', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 272, reg: 'C-GARJ', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 273, reg: 'C-GARO', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 276, reg: 'C-GBHO', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 277, reg: 'C-GBHR', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 278, reg: 'C-GBHY', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 279, reg: 'C-GBHZ', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 281, reg: 'C-GBIJ', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 283, reg: 'C-GBIM', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 284, reg: 'C-GBIN', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 290, reg: 'C-GSJB', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 292, reg: 'C-GJVY', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 296, reg: 'C-GKOB', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({fin: 468, reg: 'C-FJOK', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({fin: 469, reg: 'C-FJOU', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({fin: 470, reg: 'C-FJQD', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({fin: 471, reg: 'C-FJQH', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({fin: 472, reg: 'C-FJQL', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({fin: 631, reg: 'C-FMWP', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 632, reg: 'C-FMWQ', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 633, reg: 'C-FMWU', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 634, reg: 'C-FMWV', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 635, reg: 'C-FMWY', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 636, reg: 'C-FMXC', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 642, reg: 'C-GSCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 645, reg: 'C-GBZR', type: 'B767', specific_type: 'B767-38EER', operator: 'Rouge'}),
        knex('fins').insert({fin: 646, reg: 'C-GDUZ', type: 'B767', specific_type: 'B767-38EER', operator: 'Rouge'}),
        knex('fins').insert({fin: 647, reg: 'C-GEOQ', type: 'B767', specific_type: 'B767-375ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 648, reg: 'C-GEOU', type: 'B767', specific_type: 'B767-375ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 656, reg: 'C-GHLA', type: 'B767', specific_type: 'B767-35HER', operator: 'Rouge'}),
        knex('fins').insert({fin: 657, reg: 'C-GHLK', type: 'B767', specific_type: 'B767-35HER', operator: 'Rouge'}),
        knex('fins').insert({fin: 658, reg: 'C-GHLQ', type: 'B767', specific_type: 'B767-36NER', operator: 'Rouge'}),
        knex('fins').insert({fin: 659, reg: 'C-GHLT', type: 'B767', specific_type: 'B767-36NER', operator: 'Rouge'}),
        knex('fins').insert({fin: 660, reg: 'C-GHLU', type: 'B767', specific_type: 'B767-36NER', operator: 'Rouge'}),
        knex('fins').insert({fin: 661, reg: 'C-GHLV', type: 'B767', specific_type: 'B767-36NER', operator: 'Rouge'}),
        knex('fins').insert({fin: 675, reg: 'C-FJZK', type: 'B767', specific_type: 'B767-3Q8ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 676, reg: 'C-FMLV', type: 'B767', specific_type: 'B767-316ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 677, reg: 'C-FMLZ', type: 'B767', specific_type: 'B767-316ER', operator: 'Rouge'}),
        knex('fins').insert({fin: 691, reg: 'C-GHPE', type: 'B767', specific_type: 'B767-33AER', operator: 'Rouge'}),
        knex('fins').insert({fin: 692, reg: 'C-GHPN', type: 'B767', specific_type: 'B767-33AER', operator: 'Rouge'}),
        knex('fins').insert({fin: 693, reg: 'C-FIYA', type: 'B767', specific_type: 'B767-33AER', operator: 'Rouge'}),
        knex('fins').insert({fin: 694, reg: 'C-FIYE', type: 'B767', specific_type: 'B767-33AER', operator: 'Rouge'}),
        knex('fins').insert({fin: 371, reg: 'C-FEIQ', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 372, reg: 'C-FEIX', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 373, reg: 'C-FEJB', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 374, reg: 'C-FEJC', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 375, reg: 'C-FEJD', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 376, reg: 'C-FEJF', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 377, reg: 'C-FEJL', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 378, reg: 'C-FEJP', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 379, reg: 'C-FEJY', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 380, reg: 'C-FEKD', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 381, reg: 'C-FEKH', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 382, reg: 'C-FEKI', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 383, reg: 'C-FEKJ', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 384, reg: 'C-FEKS', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 385, reg: 'C-FFYG', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 386, reg: 'C-FUJA', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 387, reg: 'C-FJBO', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 388, reg: 'C-FXJC', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 389, reg: 'C-FUJE', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 390, reg: 'C-FXJF', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 391, reg: 'C-FRQK', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 392, reg: 'C-FRQM', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 393, reg: 'C-FRQN', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 394, reg: 'C-FRQP', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 395, reg: 'C-FRQW', type: 'E175', specific_type: 'E175', operator: 'Sky Regional'}),
        knex('fins').insert({fin: 951, reg: 'C-GGGA', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 952, reg: 'C-GVGA', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 953, reg: 'C-GHGA', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 954, reg: 'C-GZGA', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 955, reg: 'C-GWGA', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 956, reg: 'C-GMGA', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 957, reg: 'C-GORA', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 958, reg: 'C-GORC', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 959, reg: 'C-GORF', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 964, reg: 'C-GAAR', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 965, reg: 'C-GAAS', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 966, reg: 'C-GAAU', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 974, reg: 'C-GORN', type: 'B1900', specific_type: 'B1900D', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 100, reg: 'C-FSKM', type: 'CRJ', specific_type: 'CRJ-100ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 101, reg: 'C-FWJF', type: 'CRJ', specific_type: 'CRJ-100ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 102, reg: 'C-FWRS', type: 'CRJ', specific_type: 'CRJ-100ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 103, reg: 'C-FWJI', type: 'CRJ', specific_type: 'CRJ-100ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 104, reg: 'C-FWRT', type: 'CRJ', specific_type: 'CRJ-100ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 105, reg: 'C-FWRR', type: 'CRJ', specific_type: 'CRJ-100ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 106, reg: 'C-GTJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 107, reg: 'C-GZJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 108, reg: 'C-GNJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 110, reg: 'C-GXJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 111, reg: 'C-GOJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 112, reg: 'C-GKEM', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 113, reg: 'C-GKEJ', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 114, reg: 'C-GKEK', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 115, reg: 'C-GKEP', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 116, reg: 'C-GKFR', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 117, reg: 'C-GKGC', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 118, reg: 'C-GKEZ', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Air Georgian'}),
        knex('fins').insert({fin: 913, reg: 'C-FCMV', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 915, reg: 'C-FCME', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 916, reg: 'C-FCMB', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 917, reg: 'C-FCMO', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 918, reg: 'C-FCMR', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 919, reg: 'C-FCMU', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 920, reg: 'C-GCMA', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 922, reg: 'C-GFSV', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 923, reg: 'C-GGBY', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 960, reg: 'C-GCML', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 961, reg: 'C-FCMP', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 962, reg: 'C-FCMN', type: 'B1900', specific_type: 'B1900D', operator: 'CMA'}),
        knex('fins').insert({fin: 963, reg: 'C-GAAT', type: 'B1900', specific_type: 'B1900D', operator: 'EVAS'}),
        knex('fins').insert({fin: 970, reg: 'C-GORI', type: 'B1900', specific_type: 'B1900D', operator: 'EVAS'}),
        knex('fins').insert({fin: 974, reg: 'C-GORN', type: 'B1900', specific_type: 'B1900D', operator: 'EVAS'}),
        knex('fins').insert({fin: 157, reg: 'C-GJZJ', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 161, reg: 'C-GJZZ', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 162, reg: 'C-FDJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 163, reg: 'C-FEJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 164, reg: 'C-FFJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 165, reg: 'C-FIJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 166, reg: 'C-FZJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 167, reg: 'C-GGJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 168, reg: 'C-GMJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 171, reg: 'C-GQJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 173, reg: 'C-GUJA', type: 'CRJ', specific_type: 'CRJ-200LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 184, reg: 'C-GKER', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Jazz'}),
        knex('fins').insert({fin: 185, reg: 'C-GKEU', type: 'CRJ', specific_type: 'CRJ-200ER', operator: 'Jazz'}),
        knex('fins').insert({fin: 301, reg: 'C-GMON', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 302, reg: 'C-GNON', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 303, reg: 'C-GUON', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 304, reg: 'C-GVON', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 305, reg: 'C-FMDW', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 306, reg: 'C-FJVV', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 307, reg: 'C-GABP', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 308, reg: 'C-FACF', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 309, reg: 'C-FACT', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 310, reg: 'C-FADF', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 311, reg: 'C-FACV', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 312, reg: 'C-GABO', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 313, reg: 'C-GTAQ', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 314, reg: 'C-GTAT', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 315, reg: 'C-GTAG', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 316, reg: 'C-GHTA', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 317, reg: 'C-GKTA', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 318, reg: 'C-GLTA', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 319, reg: 'C-GMTA', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 320, reg: 'C-GSTA', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 321, reg: 'C-GETA', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 322, reg: 'C-GVTA', type: 'DHC-8', specific_type: 'DHC-8-301', operator: 'Jazz'}),
        knex('fins').insert({fin: 323, reg: 'C-FTAK', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 324, reg: 'C-FJFM', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 325, reg: 'C-GEWQ', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 326, reg: 'C-FJXZ', type: 'DHC-8', specific_type: 'DHC-8-311', operator: 'Jazz'}),
        knex('fins').insert({fin: 401, reg: 'C-GGOY', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 402, reg: 'C-GKUK', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 403, reg: 'C-GGOK', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 404, reg: 'C-GGOI', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 405, reg: 'C-GGOF', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 406, reg: 'C-GGNZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 407, reg: 'C-GGNY', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 408, reg: 'C-GGNW', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 409, reg: 'C-GGNF', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 410, reg: 'C-GGND', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 411, reg: 'C-GGMU', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 412, reg: 'C-GGMZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 413, reg: 'C-GGMQ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 414, reg: 'C-GGMN', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 415, reg: 'C-GGMI', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 416, reg: 'C-GGAH', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 417, reg: 'C-GGBF', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 418, reg: 'C-GGCI', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 419, reg: 'C-GGDU', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 420, reg: 'C-GGFJ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 421, reg: 'C-GGFP', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 422, reg: 'C-GBJZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 423, reg: 'C-GJZG', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 424, reg: 'C-GJZX', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 425, reg: 'C-GIJZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 426, reg: 'C-GSJZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 427, reg: 'C-GJZK', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 428, reg: 'C-GUJZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 429, reg: 'C-GVJZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 430, reg: 'C-GXJZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 431, reg: 'C-GYJZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 432, reg: 'C-GJZY', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 433, reg: 'C-GJZA', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 434, reg: 'C-GJZD', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 489, reg: 'C-FSRJ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 490, reg: 'C-FSRN', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 491, reg: 'C-FSRW', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 492, reg: 'C-FSRY', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 493, reg: 'C-FSRZ', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 494, reg: 'C-GJZH', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 495, reg: 'C-GJZC', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 496, reg: 'C-GJZR', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 497, reg: 'C-GJZF', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 498, reg: 'C-GJZN', type: 'DHC-8', specific_type: 'DHC-8-402Q', operator: 'Jazz'}),
        knex('fins').insert({fin: 701, reg: 'C-GJAZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 702, reg: 'C-FBJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 703, reg: 'C-FCJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 704, reg: 'C-FDJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 705, reg: 'C-FJJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 706, reg: 'C-FKJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 707, reg: 'C-FLJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 708, reg: 'C-FAJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 709, reg: 'C-FTJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 710, reg: 'C-FUJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 711, reg: 'C-GDJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 712, reg: 'C-GFJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 713, reg: 'C-GLJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 714, reg: 'C-GNJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 715, reg: 'C-GOJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 716, reg: 'C-GPJZ', type: 'CRJ', specific_type: 'CRJ-705LR', operator: 'Jazz'}),
        knex('fins').insert({fin: 717, reg: 'C-FJZD', type: 'CRJ', specific_type: 'CRJ-900ER', operator: 'Jazz'}),
        knex('fins').insert({fin: 718, reg: 'C-FJZL', type: 'CRJ', specific_type: 'CRJ-900ER', operator: 'Jazz'}),
        knex('fins').insert({fin: 719, reg: 'C-GJZS', type: 'CRJ', specific_type: 'CRJ-900ER', operator: 'Jazz'}),
        knex('fins').insert({fin: 720, reg: 'C-GJZT', type: 'CRJ', specific_type: 'CRJ-900ER', operator: 'Jazz'}),
        knex('fins').insert({fin: 721, reg: 'C-GJZV', type: 'CRJ', specific_type: 'CRJ-900ER', operator: 'Jazz'}),
        knex('fins').insert({fin: 815, reg: 'C-GKON', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 819, reg: 'C-FGQK', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 820, reg: 'C-FGRM', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 821, reg: 'C-FGRC', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 822, reg: 'C-FGRP', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 824, reg: 'C-FJMG', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 826, reg: 'C-GJIG', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 827, reg: 'C-GONY', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 829, reg: 'C-GONX', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 832, reg: 'C-GION', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 836, reg: 'C-FPON', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 839, reg: 'C-GONJ', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 841, reg: 'C-GONR', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 843, reg: 'C-GONW', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 844, reg: 'C-FGRY', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'}),
        knex('fins').insert({fin: 853, reg: 'C-GTAI', type: 'DHC-8', specific_type: 'DHC-8-102', operator: 'Jazz'})
      ]);
    });

};
