exports.seed = function(knex, Promise) {

  return knex('fins').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('fins').insert({id: 314, reg: 'C-FHJU', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 315, reg: 'C-FHKA', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 316, reg: 'C-FHKE', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 317, reg: 'C-FHKI', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 318, reg: 'C-FHKP', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 321, reg: 'C-FHNL', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 322, reg: 'C-FHNP', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 323, reg: 'C-FHNV', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 324, reg: 'C-FHNW', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 327, reg: 'C-FLWE', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 328, reg: 'C-FLWH', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 329, reg: 'C-FLWK', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 331, reg: 'C-FHOS', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 332, reg: 'C-FHOY', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 333, reg: 'C-FMYV', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 334, reg: 'C-FMZB', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 335, reg: 'C-FMZD', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 336, reg: 'C-FMZR', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 337, reg: 'C-FMZU', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 338, reg: 'C-FMZW', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 339, reg: 'C-FNAI', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 340, reg: 'C-FNAJ', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 341, reg: 'C-FNAN', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 342, reg: 'C-FNAP', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 344, reg: 'C-FNAW', type: 'E190', specific_type: 'E190', operator: 'Air Canada'}),
        knex('fins').insert({id: 258, reg: 'C-FYJI', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 260, reg: 'C-FYKC', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 261, reg: 'C-FYKR', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 264, reg: 'C-FZUH', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 265, reg: 'C-FZUJ', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 266, reg: 'C-FZUL', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 267, reg: 'C-GAPY', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 268, reg: 'C-GAQL', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 269, reg: 'C-GAQX', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 270, reg: 'C-GAQZ', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 271, reg: 'C-GARG', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 274, reg: 'C-GBHM', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 275, reg: 'C-GBHN', type: 'A319', specific_type: 'A319-100', comments: 'Jetz', operator: 'Air Canada'}),
        knex('fins').insert({id: 280, reg: 'C-GBIA', type: 'A319', specific_type: 'A319-100', comments: 'Jetz', operator: 'Air Canada'}),
        knex('fins').insert({id: 282, reg: 'C-GBIK', type: 'A319', specific_type: 'A319-100', comments: 'Jetz', operator: 'Air Canada'}),
        knex('fins').insert({id: 285, reg: 'C-GBIP', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 286, reg: 'C-GITP', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 287, reg: 'C-GITR', type: 'A319', specific_type: 'A319-100', operator: 'Air Canada'}),
        knex('fins').insert({id: 201, reg: 'C-FDQQ', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 202, reg: 'C-FDQV', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 203, reg: 'C-FDRH', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 204, reg: 'C-FDRK', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 205, reg: 'C-FDRP', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 206, reg: 'C-FDSN', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 207, reg: 'C-FDST', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 208, reg: 'C-FDSU', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 209, reg: 'C-FFWI', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 210, reg: 'C-FFWJ', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 211, reg: 'C-FFWM', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 212, reg: 'C-FFWN', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 213, reg: 'C-FTJO', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 215, reg: 'C-FTJQ', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 216, reg: 'C-FTJR', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 217, reg: 'C-FTJS', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 218, reg: 'C-FGYL', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 219, reg: 'C-FGYS', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 220, reg: 'C-FKCK', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 221, reg: 'C-FKCO', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 222, reg: 'C-FKCR', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 225, reg: 'C-FKPT', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 226, reg: 'C-FKOJ', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 228, reg: 'C-FPDN', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 232, reg: 'C-FMSX', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 235, reg: 'C-GJVT', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({id: 236, reg: 'C-GKOD', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({id: 237, reg: 'C-GKOE', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({id: 238, reg: 'C-FZUB', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({id: 239, reg: 'C-FXCD', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({id: 240, reg: 'C-FZQS', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({id: 241, reg: 'C-FGJI', type: 'A320', specific_type: 'A320-214', operator: 'Air Canada'}),
        knex('fins').insert({id: 242, reg: 'C-FGKH', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 401, reg: 'C-GPWG', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 402, reg: 'C-FPWE', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 403, reg: 'C-GQCA', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 404, reg: 'C-FPWD', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 405, reg: 'C-FDCA', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 408, reg: 'C-FLSS', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 411, reg: 'C-FLSU', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 415, reg: 'C-FNVU', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 416, reg: 'C-FNVV', type: 'A320', specific_type: 'A320-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 451, reg: 'C-GITU', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 452, reg: 'C-GITY', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 453, reg: 'C-GIUB', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 454, reg: 'C-GIUE', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 455, reg: 'C-GIUF', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 456, reg: 'C-GJVX', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 457, reg: 'C-GJWD', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 458, reg: 'C-GJWI', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 459, reg: 'C-GJWN', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 460, reg: 'C-GJWO', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 461, reg: 'C-FGKN', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 462, reg: 'C-FGKP', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 463, reg: 'C-FGKZ', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 464, reg: 'C-FJNX', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 473, reg: 'C-FLKX', type: 'A321', specific_type: 'A321-211', operator: 'Air Canada'}),
        knex('fins').insert({id: 637, reg: 'C-FPCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 638, reg: 'C-FTCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 639, reg: 'C-FXCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 640, reg: 'C-FOCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 641, reg: 'C-GLCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 681, reg: 'C-FCAB', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 682, reg: 'C-FCAE', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 683, reg: 'C-FCAF', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 684, reg: 'C-FCAG', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 685, reg: 'C-GHOZ', type: 'B767', specific_type: 'B767-375ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 701, reg: 'C-FIUA', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({id: 702, reg: 'C-FIUF', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({id: 703, reg: 'C-FIUJ', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({id: 704, reg: 'C-FIVK', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({id: 705, reg: 'C-FNND', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({id: 706, reg: 'C-FNNH', type: 'B777', specific_type: 'B777-233LR', operator: 'Air Canada'}),
        knex('fins').insert({id: 731, reg: 'C-FITL', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 732, reg: 'C-FITU', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 733, reg: 'C-FITW', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 734, reg: 'C-FIUL', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 735, reg: 'C-FIUR', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 736, reg: 'C-FIUV', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 737, reg: 'C-FIUW', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 738, reg: 'C-FIVM', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 739, reg: 'C-FRAM', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 740, reg: 'C-FIVQ', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 741, reg: 'C-FIVR', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 742, reg: 'C-FIVS', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 743, reg: 'C-FIVW', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 744, reg: 'C-FIVX', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 745, reg: 'C-FNNQ', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 746, reg: 'C-FNNU', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 747, reg: 'C-FNNW', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 748, reg: 'C-FJZS', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 749, reg: 'C-FKAU', type: 'B777', specific_type: 'B777-333ER', operator: 'Air Canada'}),
        knex('fins').insert({id: 801, reg: 'C-GHPQ', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({id: 802, reg: 'C-GHPT', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({id: 803, reg: 'C-GHPU', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({id: 804, reg: 'C-GHPV', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({id: 805, reg: 'C-GHPX', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({id: 806, reg: 'C-GHPY', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({id: 807, reg: 'C-GHQQ', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({id: 808, reg: 'C-GHQY', type: 'B787', specific_type: 'B787-8', operator: 'Air Canada'}),
        knex('fins').insert({id: 831, reg: 'C-FNOE', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 832, reg: 'C-FNOG', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 833, reg: 'C-FNOH', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 834, reg: 'C-FNOI', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 835, reg: 'C-FGDT', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 836, reg: 'C-FGDX', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 837, reg: 'C-FGDZ', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 838, reg: 'C-FGEI', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 839, reg: 'C-FGEO', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 840, reg: 'C-FGFZ', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 841, reg: 'C-FPQB', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 842, reg: 'C-FGHZ', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 843, reg: 'C-FKSV', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 844, reg: 'C-FRSA', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 845, reg: 'C-FRSE', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 846, reg: 'C-FRSI', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 847, reg: 'C-FRSO', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 848, reg: 'C-FRSR', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 849, reg: 'C-FRTG', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 850, reg: 'C-FRTU', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 851, reg: 'C-FRTW', type: 'B787', specific_type: 'B787-9', operator: 'Air Canada'}),
        knex('fins').insert({id: 931, reg: 'C-GFAF', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({id: 932, reg: 'C-GFAH', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({id: 933, reg: 'C-GFAJ', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({id: 934, reg: 'C-GFUR', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({id: 935, reg: 'C-GHKR', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({id: 936, reg: 'C-GHKW', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({id: 937, reg: 'C-GHKX', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({id: 938, reg: 'C-GHLM', type: 'A330', specific_type: 'A330-300', operator: 'Air Canada'}),
        knex('fins').insert({id: 251, reg: 'C-FYNS', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 252, reg: 'C-FYIY', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 255, reg: 'C-FYJE', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 256, reg: 'C-FYJG', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 257, reg: 'C-FYJH', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 259, reg: 'C-FYJP', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 262, reg: 'C-FYKW', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 263, reg: 'C-FZUG', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 272, reg: 'C-GARJ', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 273, reg: 'C-GARO', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 276, reg: 'C-GBHO', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 277, reg: 'C-GBHR', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 278, reg: 'C-GBHY', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 279, reg: 'C-GBHZ', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 281, reg: 'C-GBIJ', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 283, reg: 'C-GBIM', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 284, reg: 'C-GBIN', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 290, reg: 'C-GSJB', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 292, reg: 'C-GJVY', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 296, reg: 'C-GKOB', type: 'A319', specific_type: 'A319-100', operator: 'Rouge'}),
        knex('fins').insert({id: 468, reg: 'C-FJOK', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({id: 469, reg: 'C-FJOU', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({id: 470, reg: 'C-FJQD', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({id: 471, reg: 'C-FJQH', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({id: 472, reg: 'C-FJQL', type: 'A321', specific_type: 'A321-211', operator: 'Rouge'}),
        knex('fins').insert({id: 631, reg: 'C-FMWP', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({id: 632, reg: 'C-FMWQ', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({id: 633, reg: 'C-FMWU', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({id: 634, reg: 'C-FMWV', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({id: 635, reg: 'C-FMWY', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({id: 636, reg: 'C-FMXC', type: 'B767', specific_type: 'B767-333ER', operator: 'Rouge'}),
        knex('fins').insert({id: 642, reg: 'C-GSCA', type: 'B767', specific_type: 'B767-375ER', operator: 'Rouge'}),
        knex('fins').insert({id: 645, reg: 'C-GBZR', type: 'B767', specific_type: 'B767-38EER', operator: 'Rouge'}),
        knex('fins').insert({id: 646, reg: 'C-GDUZ', type: 'B767', specific_type: 'B767-38EER', operator: 'Rouge'}),
        knex('fins').insert({id: 647, reg: 'C-GEOQ', type: 'B767', specific_type: 'B767-375ER', operator: 'Rouge'}),
        knex('fins').insert({id: 648, reg: 'C-GEOU', type: 'B767', specific_type: 'B767-375ER', operator: 'Rouge'}),
        knex('fins').insert({id: 656, reg: 'C-GHLA', type: 'B767', specific_type: 'B767-35HER', operator: 'Rouge'}),
        knex('fins').insert({id: 657, reg: 'C-GHLK', type: 'B767', specific_type: 'B767-35HER', operator: 'Rouge'}),
        knex('fins').insert({id: 658, reg: 'C-GHLQ', type: 'B767', specific_type: 'B767-36NER', operator: 'Rouge'}),
        knex('fins').insert({id: 659, reg: 'C-GHLT', type: 'B767', specific_type: 'B767-36NER', operator: 'Rouge'}),
        knex('fins').insert({id: 660, reg: 'C-GHLU', type: 'B767', specific_type: 'B767-36NER', operator: 'Rouge'}),
        knex('fins').insert({id: 661, reg: 'C-GHLV', type: 'B767', specific_type: 'B767-36NER', operator: 'Rouge'}),
        knex('fins').insert({id: 675, reg: 'C-FJZK', type: 'B767', specific_type: 'B767-3Q8ER', operator: 'Rouge'}),
        knex('fins').insert({id: 676, reg: 'C-FMLV', type: 'B767', specific_type: 'B767-316ER', operator: 'Rouge'}),
        knex('fins').insert({id: 677, reg: 'C-FMLZ', type: 'B767', specific_type: 'B767-316ER', operator: 'Rouge'}),
        knex('fins').insert({id: 691, reg: 'C-GHPE', type: 'B767', specific_type: 'B767-33AER', operator: 'Rouge'}),
        knex('fins').insert({id: 692, reg: 'C-GHPN', type: 'B767', specific_type: 'B767-33AER', operator: 'Rouge'}),
        knex('fins').insert({id: 693, reg: 'C-FIYA', type: 'B767', specific_type: 'B767-33AER', operator: 'Rouge'}),
        knex('fins').insert({id: 694, reg: 'C-FIYE', type: 'B767', specific_type: 'B767-33AER', operator: 'Rouge'})
      ]);
    });

};
